//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyFunResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyFunResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MyFunResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Holder.
        /// </summary>
        internal static string AccountHolder {
            get {
                return ResourceManager.GetString("AccountHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Compare.
        /// </summary>
        internal static string AddtoCompare {
            get {
                return ResourceManager.GetString("AddtoCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        internal static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AptNo.
        /// </summary>
        internal static string AptNo {
            get {
                return ResourceManager.GetString("AptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AptNo required.
        /// </summary>
        internal static string AptNoRequired {
            get {
                return ResourceManager.GetString("AptNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is AROUTBALANCE. Do you wish to continue ?.
        /// </summary>
        internal static string AROUTBALANCE {
            get {
                return ResourceManager.GetString("AROUTBALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is BADDEBT. Do you wish to continue ?.
        /// </summary>
        internal static string BADDEBT {
            get {
                return ResourceManager.GetString("BADDEBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is BADDEBTOFFI. Do you wish to continue ?.
        /// </summary>
        internal static string BADDEBTOFFI {
            get {
                return ResourceManager.GetString("BADDEBTOFFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment is pending for further review..
        /// </summary>
        internal static string BadDebt_Submit_Mes {
            get {
                return ResourceManager.GetString("BadDebt_Submit_Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        internal static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityName.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityName required.
        /// </summary>
        internal static string CityNameRequired {
            get {
                return ResourceManager.GetString("CityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        internal static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Method.
        /// </summary>
        internal static string ContactMethod {
            get {
                return ResourceManager.GetString("ContactMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        internal static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type Details.
        /// </summary>
        internal static string ContactTypeDetails {
            get {
                return ResourceManager.GetString("ContactTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that this enrollment
        ///will not overrule any Early Termination
        ///Fees you may incur from breaking
        ///your contract..
        /// </summary>
        internal static string ContractExpYes {
            get {
                return ResourceManager.GetString("ContractExpYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract_Term.
        /// </summary>
        internal static string Contract_Term {
            get {
                return ResourceManager.GetString("Contract_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Check.
        /// </summary>
        internal static string CreditCheck {
            get {
                return ResourceManager.GetString("CreditCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit check failed in internal rule: {0}&lt;/br&gt;. Matched customer number(s):{1}.
        /// </summary>
        internal static string CreditCheckError_InternalRule {
            get {
                return ResourceManager.GetString("CreditCheckError_InternalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If we should have found you via the address provided, please give us a call at 877.437.7440 to see if you qualify for a smaller deposit. .
        /// </summary>
        internal static string creditCheckError_popup_ifNomsg {
            get {
                return ResourceManager.GetString("creditCheckError_popup_ifNomsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your old address and social security number again to try to find your  credit history. .
        /// </summary>
        internal static string creditCheckError_popup_ifYesmsg {
            get {
                return ResourceManager.GetString("creditCheckError_popup_ifYesmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to determine your credit history. Do you have another address that could help us find your credit score?.
        /// </summary>
        internal static string creditCheckError_popup_message {
            get {
                return ResourceManager.GetString("creditCheckError_popup_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit has been set as Fraud Alert..
        /// </summary>
        internal static string CreditCheckFraudIntbfrSMS {
            get {
                return ResourceManager.GetString("CreditCheckFraudIntbfrSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit has been set as Fraud Alert.&lt;br&gt;
        ///If click Continue then the enrollment will be on hold until verification is confirmed with the customer.&lt;br&gt;
        ///Click on Stop button to go to main page for new enrollment..
        /// </summary>
        internal static string Credit_Check_Fraud {
            get {
                return ResourceManager.GetString("Credit_Check_Fraud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Electicity Contract.
        /// </summary>
        internal static string CurrentElecticityContract_popupCaption {
            get {
                return ResourceManager.GetString("CurrentElecticityContract_popupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that if you are still under contract with another electric company as of the selected date above, this enrollment will not overrule  any Early Termination Fees you may incur from breaking your contract. .
        /// </summary>
        internal static string CurrentElecticityContract_popupMsg {
            get {
                return ResourceManager.GetString("CurrentElecticityContract_popupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        internal static string CustomerDetails {
            get {
                return ResourceManager.GetString("CustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC Code Required.
        /// </summary>
        internal static string CVCCodeReq {
            get {
                return ResourceManager.GetString("CVCCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth invalid.
        /// </summary>
        internal static string DateOfBirthInvalid {
            get {
                return ResourceManager.GetString("DateOfBirthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth required.
        /// </summary>
        internal static string DateOfBirthRequired {
            get {
                return ResourceManager.GetString("DateOfBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to determine your credit history. To avoid paying a deposit of $ {0} , please provide a previous address that we can use to help identify you.
        /// </summary>
        internal static string DepositAmount {
            get {
                return ResourceManager.GetString("DepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to determine your credit history. Please provide a previous address that we can use to help identify you..
        /// </summary>
        internal static string depositAmt_note {
            get {
                return ResourceManager.GetString("depositAmt_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is DISHON. Do you wish to continue ?.
        /// </summary>
        internal static string DISHON {
            get {
                return ResourceManager.GetString("DISHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is DISHON_CHQ. Do you wish to continue ?.
        /// </summary>
        internal static string DISHON_CHQ {
            get {
                return ResourceManager.GetString("DISHON_CHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is DISHON_DD. Do you wish to continue ?.
        /// </summary>
        internal static string DISHON_DD {
            get {
                return ResourceManager.GetString("DISHON_DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is DISHON_PN. Do you wish to continue ?.
        /// </summary>
        internal static string DISHON_PN {
            get {
                return ResourceManager.GetString("DISHON_PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwelling Type.
        /// </summary>
        internal static string DwellingType {
            get {
                return ResourceManager.GetString("DwellingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFLFileName.
        /// </summary>
        internal static string EFLFileName {
            get {
                return ResourceManager.GetString("EFLFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll.
        /// </summary>
        internal static string Enroll {
            get {
                return ResourceManager.GetString("Enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Successfull.
        /// </summary>
        internal static string EnrollmentSuccessfull {
            get {
                return ResourceManager.GetString("EnrollmentSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment rejected successfully.
        /// </summary>
        internal static string Enroll_rejected {
            get {
                return ResourceManager.GetString("Enroll_rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your service address here.
        /// </summary>
        internal static string EnterServiceAddressHere {
            get {
                return ResourceManager.GetString("EnterServiceAddressHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your SSN.
        /// </summary>
        internal static string enterSSN {
            get {
                return ResourceManager.GetString("enterSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESIID.
        /// </summary>
        internal static string ESIID {
            get {
                return ResourceManager.GetString("ESIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESIID not selected.
        /// </summary>
        internal static string ESIIDNotSelected {
            get {
                return ResourceManager.GetString("ESIIDNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESIID/Service Address.
        /// </summary>
        internal static string ESIIDORServiceAddress {
            get {
                return ResourceManager.GetString("ESIIDORServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESIID required.
        /// </summary>
        internal static string ESIIDRequired {
            get {
                return ResourceManager.GetString("ESIIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Month Required.
        /// </summary>
        internal static string ExpMonthReq {
            get {
                return ResourceManager.GetString("ExpMonthReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Year Required.
        /// </summary>
        internal static string ExpYearReq {
            get {
                return ResourceManager.GetString("ExpYearReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected address requires additional review. The enrollment will be placed on hold for review. Do you wish to continue?.
        /// </summary>
        internal static string ExternalHold_mes {
            get {
                return ResourceManager.GetString("ExternalHold_mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is FEWO. Do you wish to continue ?.
        /// </summary>
        internal static string FEWO {
            get {
                return ResourceManager.GetString("FEWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name required.
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUN Web Enrollment.
        /// </summary>
        internal static string FUNWebEnrollment {
            get {
                return ResourceManager.GetString("FUNWebEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Social Security Number.
        /// </summary>
        internal static string InvalidSSN {
            get {
                return ResourceManager.GetString("InvalidSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name required.
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This meter is Non AMS and is not eligible for Prepaid service. Please check your entry, &lt;br&gt;contact Frontier Utilities for support, or you may continue with a Postpaid selection..
        /// </summary>
        internal static string Mes_AmsNonAms {
            get {
                return ResourceManager.GetString("Mes_AmsNonAms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Initial.
        /// </summary>
        internal static string MiddleInitial {
            get {
                return ResourceManager.GetString("MiddleInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name required.
        /// </summary>
        internal static string MiddleNameRequired {
            get {
                return ResourceManager.GetString("MiddleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Age is 18 years.
        /// </summary>
        internal static string MinAge {
            get {
                return ResourceManager.GetString("MinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 3 chars required.
        /// </summary>
        internal static string MinThreeCharsRequired {
            get {
                return ResourceManager.GetString("MinThreeCharsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        internal static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileNo invalid.
        /// </summary>
        internal static string MobileNoInvalid {
            get {
                return ResourceManager.GetString("MobileNoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileNo required.
        /// </summary>
        internal static string MobileNoRequired {
            get {
                return ResourceManager.GetString("MobileNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveIn.
        /// </summary>
        internal static string MoveIn {
            get {
                return ResourceManager.GetString("MoveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Type.
        /// </summary>
        internal static string MoveType {
            get {
                return ResourceManager.GetString("MoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Cancallation fee.
        /// </summary>
        internal static string NoCancallationfee {
            get {
                return ResourceManager.GetString("NoCancallationfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online_Only_YN.
        /// </summary>
        internal static string Online_Only_YN {
            get {
                return ResourceManager.GetString("Online_Only_YN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Empty.
        /// </summary>
        internal static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords mismatch.
        /// </summary>
        internal static string PasswordsMismatch {
            get {
                return ResourceManager.GetString("PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your tracking number {0}..
        /// </summary>
        internal static string PendnfEnroll_Mes {
            get {
                return ResourceManager.GetString("PendnfEnroll_Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is PENDSWOUT.Do you wish to continue.
        /// </summary>
        internal static string PENDSWOUT {
            get {
                return ResourceManager.GetString("PENDSWOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is PENDSWOUT and AROUTBALANCE. Do you wish to continue ?.
        /// </summary>
        internal static string PENDSWOUT_and_AROUTBALANCE {
            get {
                return ResourceManager.GetString("PENDSWOUT_and_AROUTBALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        internal static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNo invalid.
        /// </summary>
        internal static string PhoneNoInvalid {
            get {
                return ResourceManager.GetString("PhoneNoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans available for your Location.
        /// </summary>
        internal static string PlansAvailableYourLocation {
            get {
                return ResourceManager.GetString("PlansAvailableYourLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostPaid.
        /// </summary>
        internal static string PostPaid {
            get {
                return ResourceManager.GetString("PostPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Of Attorney.
        /// </summary>
        internal static string PowerOfAttorney {
            get {
                return ResourceManager.GetString("PowerOfAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrePaid.
        /// </summary>
        internal static string PrePaid {
            get {
                return ResourceManager.GetString("PrePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information entered matches our records. The enrollment will be placed on hold for review. Do you wish to continue?.
        /// </summary>
        internal static string PrepayFail {
            get {
                return ResourceManager.GetString("PrepayFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepaid services is not eligible for House. Please check your entry, contact Frontier Utilities for support, or you may continue with a Postpaid selection..
        /// </summary>
        internal static string Prepay_House {
            get {
                return ResourceManager.GetString("Prepay_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepay_YN.
        /// </summary>
        internal static string Prepay_YN {
            get {
                return ResourceManager.GetString("Prepay_YN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PricePlanID.
        /// </summary>
        internal static string PricePlanID {
            get {
                return ResourceManager.GetString("PricePlanID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Product.
        /// </summary>
        internal static string productHeader {
            get {
                return ResourceManager.GetString("productHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductID.
        /// </summary>
        internal static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not selected.
        /// </summary>
        internal static string ProductNotSelected {
            get {
                return ResourceManager.GetString("ProductNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductSelected.
        /// </summary>
        internal static string ProductSelected {
            get {
                return ResourceManager.GetString("ProductSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product_Desc.
        /// </summary>
        internal static string Product_Desc {
            get {
                return ResourceManager.GetString("Product_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate(in Cents).
        /// </summary>
        internal static string RateInCents {
            get {
                return ResourceManager.GetString("RateInCents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected address has a  {0}. Do you wish to continue?.
        /// </summary>
        internal static string ReasonDesc {
            get {
                return ResourceManager.GetString("ReasonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref/Promo Code.
        /// </summary>
        internal static string RefORPromoCode {
            get {
                return ResourceManager.GetString("RefORPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to MyFUNAccount.
        /// </summary>
        internal static string RegistertoMyFUNAccount {
            get {
                return ResourceManager.GetString("RegistertoMyFUNAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        internal static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password Empty.
        /// </summary>
        internal static string RetypePasswordEmpty {
            get {
                return ResourceManager.GetString("RetypePasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are switching service from another REP to Frontier Utilities, you may cancel this agreement without penalty or fee within the first 3 federal business days after you receive this Agreement. You may cancel the Agreement by:
        ///*calling 1-866-926-8192
        ///*writing to 5444 Westheimer Rd., Suite 1100, Houston, TX 77056
        ///*sending a fax to 1-866-926-8193
        ///*sending an email to care@frontierutilities.com
        ///no later than midnight of the 3rd federal business day. Please include:
        ///*your name and service address,
        ///*yo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Right_of_Recission {
            get {
                return ResourceManager.GetString("Right_of_Recission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Right of Recission is not applicable to an applicant requesting a move-in..
        /// </summary>
        internal static string Right_of_Recission2 {
            get {
                return ResourceManager.GetString("Right_of_Recission2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand that enrollment for service can be made only by an applicant or the applicant&apos;s authorized agent, and, in accordance with that requirement, I certify that I am at least 18 years of age and legally authorized to select or change Retail Electric Providers (REPs) for the address listed above. I authorize TXU Energy to become my new REP in place of my current REP, if applicable. I authorize TXU Energy to act as my agent to perform the necessary tasks to establish my electricity service account and, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Right_of_Recission3 {
            get {
                return ResourceManager.GetString("Right_of_Recission3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By.
        /// </summary>
        internal static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Product.
        /// </summary>
        internal static string SelectaProduct {
            get {
                return ResourceManager.GetString("SelectaProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Service Address as Billing Address.
        /// </summary>
        internal static string ServiceAddAsBilling {
            get {
                return ResourceManager.GetString("ServiceAddAsBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Address.
        /// </summary>
        internal static string ServiceAddress {
            get {
                return ResourceManager.GetString("ServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Service Address.
        /// </summary>
        internal static string ServiceAddressReq {
            get {
                return ResourceManager.GetString("ServiceAddressReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        internal static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN.
        /// </summary>
        internal static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN required.
        /// </summary>
        internal static string SSNRequired {
            get {
                return ResourceManager.GetString("SSNRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateName required.
        /// </summary>
        internal static string StateNameRequired {
            get {
                return ResourceManager.GetString("StateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step1: Select a Product.
        /// </summary>
        internal static string Step1Header {
            get {
                return ResourceManager.GetString("Step1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetName.
        /// </summary>
        internal static string StreetName {
            get {
                return ResourceManager.GetString("StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetName required.
        /// </summary>
        internal static string StreetNameRequired {
            get {
                return ResourceManager.GetString("StreetNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetNo.
        /// </summary>
        internal static string StreetNo {
            get {
                return ResourceManager.GetString("StreetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetNo required.
        /// </summary>
        internal static string StreetNoRequired {
            get {
                return ResourceManager.GetString("StreetNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch/MoveIn Date.
        /// </summary>
        internal static string SwitchMoveInDate {
            get {
                return ResourceManager.GetString("SwitchMoveInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected address is SWITCH_HOLD. Do you wish to continue ?.
        /// </summary>
        internal static string SWITCH_HOLD {
            get {
                return ResourceManager.GetString("SWITCH_HOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDSP_Code.
        /// </summary>
        internal static string TDSP_Code {
            get {
                return ResourceManager.GetString("TDSP_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Not able to Identifiy your TDSP &lt;br&gt; Please Call Frontier at 1-866-926-8192.
        /// </summary>
        internal static string TDSP_NullPrompt {
            get {
                return ResourceManager.GetString("TDSP_NullPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit_Price.
        /// </summary>
        internal static string Unit_Price {
            get {
                return ResourceManager.GetString("Unit_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Amount.
        /// </summary>
        internal static string ValidAmount {
            get {
                return ResourceManager.GetString("ValidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Credit Card Number.
        /// </summary>
        internal static string ValidCCNumber {
            get {
                return ResourceManager.GetString("ValidCCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Amount.
        /// </summary>
        internal static string ValidDollars {
            get {
                return ResourceManager.GetString("ValidDollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid kWh.
        /// </summary>
        internal static string ValidKWH {
            get {
                return ResourceManager.GetString("ValidKWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Number is.
        /// </summary>
        internal static string YourAccountNumberIs {
            get {
                return ResourceManager.GetString("YourAccountNumberIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode required.
        /// </summary>
        internal static string ZipCodeRequired {
            get {
                return ResourceManager.GetString("ZipCodeRequired", resourceCulture);
            }
        }
    }
}
