//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyFunResources_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyFunResources_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MyFunResources_es", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular de la cuenta.
        /// </summary>
        internal static string AccountHolder {
            get {
                return ResourceManager.GetString("AccountHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Cuenta.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir para comparar.
        /// </summary>
        internal static string AddtoCompare {
            get {
                return ResourceManager.GetString("AddtoCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apartamento.
        /// </summary>
        internal static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de apartamento.
        /// </summary>
        internal static string AptNo {
            get {
                return ResourceManager.GetString("AptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de apartamento requerido.
        /// </summary>
        internal static string AptNoRequired {
            get {
                return ResourceManager.GetString("AptNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de Facturación.
        /// </summary>
        internal static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to negocios.
        /// </summary>
        internal static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la ciudad.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la ciudad requiere.
        /// </summary>
        internal static string CityNameRequired {
            get {
                return ResourceManager.GetString("CityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comparar.
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de contacto.
        /// </summary>
        internal static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de contacto.
        /// </summary>
        internal static string ContactMethod {
            get {
                return ResourceManager.GetString("ContactMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de contactos.
        /// </summary>
        internal static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto Tipo Detalles.
        /// </summary>
        internal static string ContactTypeDetails {
            get {
                return ResourceManager.GetString("ContactTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenga en cuenta que esta inscripción
        ///no hacer caso omiso de cualquier cancelación anticipada
        ///Honorarios que pueda incurrir se rompa
        ///su contrato..
        /// </summary>
        internal static string ContractExpYes {
            get {
                return ResourceManager.GetString("ContractExpYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrac Term.
        /// </summary>
        internal static string Contract_Term {
            get {
                return ResourceManager.GetString("Contract_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verificación de crédito.
        /// </summary>
        internal static string CreditCheck {
            get {
                return ResourceManager.GetString("CreditCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Cliente.
        /// </summary>
        internal static string CustomerDetails {
            get {
                return ResourceManager.GetString("CustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        internal static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento válido.
        /// </summary>
        internal static string DateOfBirthinvalid {
            get {
                return ResourceManager.GetString("DateOfBirthinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento requerida.
        /// </summary>
        internal static string DateOfBirthRequired {
            get {
                return ResourceManager.GetString("DateOfBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to determine your credit history. To avoid paying a deposit of $ {0} , please provide a previous address that we can use to help identify you.
        /// </summary>
        internal static string DepositAmount {
            get {
                return ResourceManager.GetString("DepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to determine your credit history. Please provide a previous address that we can use to help identify you..
        /// </summary>
        internal static string depositAmt_note {
            get {
                return ResourceManager.GetString("depositAmt_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de vivienda.
        /// </summary>
        internal static string DwellingType {
            get {
                return ResourceManager.GetString("DwellingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFL Nombre del archivo.
        /// </summary>
        internal static string EFLFileName {
            get {
                return ResourceManager.GetString("EFLFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email no válido.
        /// </summary>
        internal static string Emailinvalid {
            get {
                return ResourceManager.GetString("Emailinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email requerido.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inscribirse.
        /// </summary>
        internal static string Enroll {
            get {
                return ResourceManager.GetString("Enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exitoso Inscripción.
        /// </summary>
        internal static string EnrollmentSuccessfull {
            get {
                return ResourceManager.GetString("EnrollmentSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su dirección de servicio aquí.
        /// </summary>
        internal static string EnterServiceAddress {
            get {
                return ResourceManager.GetString("EnterServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your SSN.
        /// </summary>
        internal static string enterSSN {
            get {
                return ResourceManager.GetString("enterSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESI ID.
        /// </summary>
        internal static string ESIID {
            get {
                return ResourceManager.GetString("ESIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESIID no seleccionado.
        /// </summary>
        internal static string ESIIDNotSelected {
            get {
                return ResourceManager.GetString("ESIIDNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESIID / Dirección de Servicio.
        /// </summary>
        internal static string ESIIDORServiceAddress {
            get {
                return ResourceManager.GetString("ESIIDORServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESIID requiere.
        /// </summary>
        internal static string ESIIDRequired {
            get {
                return ResourceManager.GetString("ESIIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Requerido.
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matriculación de Web FUN.
        /// </summary>
        internal static string FUNWebEnrollment {
            get {
                return ResourceManager.GetString("FUNWebEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ir.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to casa.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to casa.
        /// </summary>
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Número de Seguro Social.
        /// </summary>
        internal static string InvalidSSN {
            get {
                return ResourceManager.GetString("InvalidSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apellido.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido requerido.
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correo.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inicial.
        /// </summary>
        internal static string MiddleInitial {
            get {
                return ResourceManager.GetString("MiddleInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La edad mínima es de 18 años.
        /// </summary>
        internal static string MinAge {
            get {
                return ResourceManager.GetString("MinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Nombre necesario.
        /// </summary>
        internal static string MinThreeCharsRequired {
            get {
                return ResourceManager.GetString("MinThreeCharsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to móvil.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de móvil.
        /// </summary>
        internal static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number invalid.
        /// </summary>
        internal static string MobileNoInvalid {
            get {
                return ResourceManager.GetString("MobileNoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de móvil requerido.
        /// </summary>
        internal static string MobileNoRequired {
            get {
                return ResourceManager.GetString("MobileNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instalarse.
        /// </summary>
        internal static string MoveIn {
            get {
                return ResourceManager.GetString("MoveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mueva Tipo.
        /// </summary>
        internal static string MoveType {
            get {
                return ResourceManager.GetString("MoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay cuota de Cancallation.
        /// </summary>
        internal static string NoCancallationfee {
            get {
                return ResourceManager.GetString("NoCancallationfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron datos.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sólo en línea ¿Sí o no.
        /// </summary>
        internal static string Online_Only_YN {
            get {
                return ResourceManager.GetString("Online_Only_YN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña vacía.
        /// </summary>
        internal static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contraseñas desajuste.
        /// </summary>
        internal static string PasswordsMismatch {
            get {
                return ResourceManager.GetString("PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teléfono.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to número de teléfono.
        /// </summary>
        internal static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de teléfono no válido.
        /// </summary>
        internal static string PhoneNoInvalid {
            get {
                return ResourceManager.GetString("PhoneNoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes disponibles para su ubicación.
        /// </summary>
        internal static string PlansAvailableYourLocation {
            get {
                return ResourceManager.GetString("PlansAvailableYourLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postpago.
        /// </summary>
        internal static string PostPaid {
            get {
                return ResourceManager.GetString("PostPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poder.
        /// </summary>
        internal static string PowerOfAttorney {
            get {
                return ResourceManager.GetString("PowerOfAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pre Pagado.
        /// </summary>
        internal static string PrePaid {
            get {
                return ResourceManager.GetString("PrePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepago Sí o no.
        /// </summary>
        internal static string Prepay_YN {
            get {
                return ResourceManager.GetString("Prepay_YN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avance.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Plan de ID.
        /// </summary>
        internal static string PricePlanID {
            get {
                return ResourceManager.GetString("PricePlanID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to producto.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Product_es.
        /// </summary>
        internal static string productHeader {
            get {
                return ResourceManager.GetString("productHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación del producto.
        /// </summary>
        internal static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del producto no seleccionado.
        /// </summary>
        internal static string ProductNotSelected {
            get {
                return ResourceManager.GetString("ProductNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to producto seleccionado.
        /// </summary>
        internal static string ProductSelected {
            get {
                return ResourceManager.GetString("ProductSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del producto.
        /// </summary>
        internal static string Product_Desc {
            get {
                return ResourceManager.GetString("Product_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio (en centavos).
        /// </summary>
        internal static string RateInCents {
            get {
                return ResourceManager.GetString("RateInCents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencia / Código Promocional.
        /// </summary>
        internal static string RefORPromoCode {
            get {
                return ResourceManager.GetString("RefORPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse para MyFUNAccount.
        /// </summary>
        internal static string RegistertoMyFUNAccount {
            get {
                return ResourceManager.GetString("RegistertoMyFUNAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuelva a escribir la contraseña.
        /// </summary>
        internal static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuelva a escribir la contraseña vacía.
        /// </summary>
        internal static string RetypePasswordEmpty {
            get {
                return ResourceManager.GetString("RetypePasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish Right of Recission comes here.
        /// </summary>
        internal static string Right_of_Recission {
            get {
                return ResourceManager.GetString("Right_of_Recission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right_of_Recission2.
        /// </summary>
        internal static string Right_of_Recission2 {
            get {
                return ResourceManager.GetString("Right_of_Recission2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right_of_Recission3.
        /// </summary>
        internal static string Right_of_Recission3 {
            get {
                return ResourceManager.GetString("Right_of_Recission3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda Por.
        /// </summary>
        internal static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seleccionar.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un producto.
        /// </summary>
        internal static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to servicio de Dirección.
        /// </summary>
        internal static string ServiceAddress {
            get {
                return ResourceManager.GetString("ServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilice el servicio de dirección como la dirección de facturación.
        /// </summary>
        internal static string ServiceAddressAsBilling {
            get {
                return ResourceManager.GetString("ServiceAddressAsBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, entre en servicio Dirección.
        /// </summary>
        internal static string ServiceAddressReq {
            get {
                return ResourceManager.GetString("ServiceAddressReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección del servicio se requiere.
        /// </summary>
        internal static string ServiceAddressRequired {
            get {
                return ResourceManager.GetString("ServiceAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to español.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cónyuge.
        /// </summary>
        internal static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN.
        /// </summary>
        internal static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN Required.
        /// </summary>
        internal static string SSNRequired {
            get {
                return ResourceManager.GetString("SSNRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Estado.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Estado requerido.
        /// </summary>
        internal static string StateNameRequired {
            get {
                return ResourceManager.GetString("StateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step1: Select a Product_Spanish.
        /// </summary>
        internal static string Step1Header {
            get {
                return ResourceManager.GetString("Step1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Calle.
        /// </summary>
        internal static string StreetName {
            get {
                return ResourceManager.GetString("StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Calle requiere.
        /// </summary>
        internal static string StreetNameRequired {
            get {
                return ResourceManager.GetString("StreetNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de la calle.
        /// </summary>
        internal static string StreetNo {
            get {
                return ResourceManager.GetString("StreetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de la calle requiere.
        /// </summary>
        internal static string StreetNoRequired {
            get {
                return ResourceManager.GetString("StreetNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cambiar.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambie / Fecha de mudanza.
        /// </summary>
        internal static string SwitchMoveInDate {
            get {
                return ResourceManager.GetString("SwitchMoveInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código TDSP.
        /// </summary>
        internal static string TDSP_Code {
            get {
                return ResourceManager.GetString("TDSP_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Not able to Identifiy your TDSP &lt;br&gt; Please Call Frontier at 1-866-926-8192.
        /// </summary>
        internal static string TDSP_NullPrompt {
            get {
                return ResourceManager.GetString("TDSP_NullPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plazo.
        /// </summary>
        internal static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio unitario.
        /// </summary>
        internal static string Unit_Price {
            get {
                return ResourceManager.GetString("Unit_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Amount.
        /// </summary>
        internal static string ValidAmount {
            get {
                return ResourceManager.GetString("ValidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Credit Card Number.
        /// </summary>
        internal static string ValidCCNumber {
            get {
                return ResourceManager.GetString("ValidCCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Amount.
        /// </summary>
        internal static string ValidDollars {
            get {
                return ResourceManager.GetString("ValidDollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid kWh.
        /// </summary>
        internal static string ValidKWH {
            get {
                return ResourceManager.GetString("ValidKWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su número de cuenta es.
        /// </summary>
        internal static string YourAccountNumberIs {
            get {
                return ResourceManager.GetString("YourAccountNumberIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to código postal.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código postal requerida.
        /// </summary>
        internal static string ZipCodeRequired {
            get {
                return ResourceManager.GetString("ZipCodeRequired", resourceCulture);
            }
        }
    }
}
